# Generated by Django 3.2.16 on 2022-12-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='is_staff',
        ),
    ]
