# Generated by Django 3.2.16 on 2022-12-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_related_name': 'groups', 'ordering': ('id',), 'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
    ]
