# Generated by Django 3.2.16 on 2022-12-20 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20221220_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='GroupMembers', related_query_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmedia',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='groups.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='персонал'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
