# Generated by Django 3.2.16 on 2022-12-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_groupmembers_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_related_name': 'groups', 'ordering': ['id'], 'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
    ]
