# Generated by Django 3.2.16 on 2022-12-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_related_name': 'groups', 'ordering': ('id',), 'verbose_name': 'группа'},
        ),
    ]
