# Generated by Django 3.2.16 on 2022-12-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20221216_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='вопрос')),
                ('variant_a', models.CharField(max_length=300, verbose_name='ответ 1')),
                ('variant_b', models.CharField(max_length=300, verbose_name='ответ 2')),
            ],
            options={
                'verbose_name': 'Тест',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialization')),
            ],
            options={
                'verbose_name': 'результаты теста',
                'verbose_name_plural': 'результаты тестов',
            },
        ),
    ]
