# Generated by Django 3.2.16 on 2022-12-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupvacancy',
            old_name='v_name',
            new_name='vacancy_name',
        ),
    ]
