# Generated by Django 3.2.16 on 2022-12-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_groupvacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupvacancy',
            options={'default_related_name': 'group_vacancy', 'ordering': ('id',), 'verbose_name': 'вакансия'},
        ),
    ]
