# Generated by Django 3.2.16 on 2022-12-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/', verbose_name='фото')),
                ('text', models.CharField(max_length=1024, verbose_name='текст к посту')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'default_related_name': 'group_post',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/', verbose_name='фото')),
                ('text', models.CharField(max_length=1024, verbose_name='текст к посту')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'default_related_name': 'user_post',
            },
        ),
    ]
