# Generated by Django 3.2.16 on 2022-12-22 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/', verbose_name='фото')),
                ('text', models.CharField(max_length=1024, verbose_name='текст к посту')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'default_related_name': 'user_post',
            },
        ),
        migrations.CreateModel(
            name='GroupVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, verbose_name='текст к посту')),
                ('name', models.CharField(max_length=1024, verbose_name='название')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post', to='groups.group', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['id'],
                'default_related_name': 'group_post',
            },
        ),
    ]
