# Generated by Django 3.2.16 on 2022-12-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupPost',
            new_name='GroupVacancy',
        ),
    ]
