# Generated by Django 3.2.16 on 2022-12-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_grouppost_groupvacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupvacancy',
            options={'default_related_name': 'group_post', 'ordering': ['id'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
