# Generated by Django 3.2.16 on 2022-12-18 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default='static_dev/img/user.png', null=True, upload_to='images/%Y/%m/%d', verbose_name='фото')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='активная учетная запись')),
                ('is_staff', models.BooleanField(default=False, null=True, verbose_name='персонал')),
                ('is_superuser', models.BooleanField(default=False, null=True, verbose_name='админ')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'default_related_name': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.CharField(max_length=4096, null=True, verbose_name='описание')),
                ('file', models.FileField(upload_to='files', verbose_name='media')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL, verbose_name='медиа')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'default_related_name': 'media',
            },
        ),
        migrations.CreateModel(
            name='ProfileLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=2048, verbose_name='ссылка')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='ссылка на профиль')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='services.service', verbose_name='сервис')),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'ссылки',
                'default_related_name': 'links',
            },
        ),
    ]
