# Generated by Django 3.2.16 on 2022-12-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default='False', null=True, verbose_name='дата рождения'),
        ),
    ]
