# Generated by Django 3.2.16 on 2022-12-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followsu2u',
            options={},
        ),
    ]
