# Generated by Django 3.2.16 on 2022-12-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelinks',
            name='slug',
            field=models.CharField(max_length=2048, verbose_name='ссылка'),
        ),
    ]
