# Generated by Django 3.2.16 on 2022-12-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_follows_followsu2u'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followsu2u',
            options={'default_related_name': 'followers'},
        ),
    ]
