# Generated by Django 3.2.16 on 2022-12-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221218_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=1024, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='description',
            field=models.CharField(max_length=4096, null=True, verbose_name='описание'),
        ),
    ]
