# Generated by Django 3.2.16 on 2022-12-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221218_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False, null=True, verbose_name='персонал'),
        ),
    ]
