# Generated by Django 3.2.16 on 2022-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221219_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelinks',
            name='is_contact',
            field=models.BooleanField(default=False, verbose_name='контакт'),
        ),
    ]
