# Generated by Django 3.2.16 on 2022-12-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m', verbose_name='фото'),
        ),
    ]
