# Generated by Django 3.2.16 on 2022-12-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profilelinks_is_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemedia',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m', verbose_name='media'),
        ),
    ]
