# Generated by Django 3.2.16 on 2022-12-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profilemedia_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='False', upload_to='images/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='media'),
        ),
    ]
