# Generated by Django 3.2.16 on 2022-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221220_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemedia',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='файл'),
        ),
    ]
