# Generated by Django 3.2.16 on 2022-12-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='сервис')),
                ('bootstrap_icon', models.CharField(help_text='https://icons.bootstrap-5.ru/icons/\nНайдите на данном сайте нужную картинку и впишите название(на примеру: bi bi-telegram)', max_length=150, verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
                'default_related_name': 'service',
            },
        ),
    ]
