# Generated by Django 3.2.16 on 2022-12-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads/%Y/%m', verbose_name='фото')),
                ('name', models.CharField(max_length=150, verbose_name='сервис')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
                'default_related_name': 'service',
            },
        ),
    ]
