# Generated by Django 3.2.16 on 2022-12-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bootstrap_icon',
            field=models.CharField(help_text='https://icons.bootstrap-5.ru/icons/\nНайдите на данном сайте нужную картинку и впишите название(на пример: bi bi-telegram)', max_length=150, verbose_name='иконка'),
        ),
    ]
