# Generated by Django 3.2.16 on 2022-12-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_bootstrap_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'default_related_name': 'service', 'verbose_name': 'сервис'},
        ),
    ]
